checks:
    php:
        code_rating: true
        duplication: true
        fix_php_opening_tag: false
        remove_php_closing_tag: true
        one_class_per_file: true
        side_effects_or_types: false
        no_mixed_inline_html: false
        require_braces_around_control_structures: true
        php5_style_constructor: true
        no_global_keyword: false
        avoid_usage_of_logical_operators: false
        psr2_class_declaration: false
        no_underscore_prefix_in_properties: false
        no_underscore_prefix_in_methods: false
        blank_line_after_namespace_declaration: false
        single_namespace_per_use: false
        psr2_switch_declaration: true
        psr2_control_structure_declaration: false
        avoid_superglobals: false
        security_vulnerabilities: true
        no_exit: false
        use_self_instead_of_fqcn: true
        uppercase_constants: true
        simplify_boolean_return: true
        return_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        prefer_while_loop_over_for_loop: true
        parameter_doc_comments: false
        optional_parameters_at_the_end: true
        no_short_variable_names:
            minimum: '3'
        no_short_method_names:
            minimum: '3'
        no_goto: true
        no_new_line_at_end_of_file: false
        more_specific_types_in_doc_comments: true
        fix_line_ending: true
        encourage_single_quotes: true
        avoid_unnecessary_concatenation: true
        avoid_perl_style_comments: true
        avoid_multiple_statements_on_same_line: true
        avoid_fixme_comments: true

filter: {  }
coding_style:
    php:
        indentation:
            general:
                use_tabs: true
        spaces:
            around_operators:
                concatenation: true
                negation: true
            within:
                brackets: true
                array_initializer: true
                grouping: true
                function_call: true
                function_declaration: true
                if: true
                for: true
                while: true
                switch: true
                catch: true
tools:
    php_code_sniffer:
        config:
            standard: "WordPress"
